insert into books (pealkiri, autor_id, zanr) values ('Police, Adjective (Politist, adj.)', 49, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Exploding Girl, The', 43, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('The Raid: Redemption', 23, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Bangkok Dangerous', 2, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Song Is Born, A', 43, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Man Push Cart', 23, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Brazil: In the Shadow of the Stadiums', 17, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('What Richard Did', 38, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Green Man, The', 43, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Village People Radio Show (Apa khabar orang kampung)', 45, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Conan O''Brien Can''t Stop', 34, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Tai-Pan', 40, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Moulin Rouge', 20, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Hamlet', 31, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Eichmann', 12, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Viy', 30, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Little Nicholas (Le petit Nicolas)', 46, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('I Remember (Eu Me Lembro)', 15, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('All in a Night''s Work', 8, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Brooklyn''s Finest', 21, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('He Ran All the Way', 8, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Brotherhood of Justice, The', 7, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('I Saw the Sun (Günesi gördüm)', 3, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Chinese Odyssey 2002 (Tian xia wu shuang)', 5, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('My Name Is Nobody (Il Mio nome è Nessuno)', 21, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Helen of Troy', 36, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Naked Harbour (Vuosaari)', 28, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('S.W.A.T.', 6, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Other Sister, The', 41, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Rock of Ages', 22, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Secret Beyond the Door', 12, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Don''t Worry, I''m Fine (Je vais bien, ne t''en fais pas)', 26, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Spread', 50, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Cinderfella', 37, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('October Sky', 23, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Eiger Sanction, The', 11, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Shelter', 23, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Stille Nacht I: Dramolet', 32, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Merry Widow, The', 39, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Blue and the Gray, The', 34, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Cannonball Run, The', 3, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Angels with Dirty Faces', 43, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Catfish in Black Bean Sauce', 2, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Anastasia', 40, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Rango', 6, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('King and the Mockingbird, The (Le roi et l''oiseau)', 9, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Nicholas Nickleby', 8, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Muppets Most Wanted', 49, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('L''antisémite', 26, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('White Squall', 22, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Platform (Zhantai)', 7, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Perfect Holiday, The', 48, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Dangerous Game', 24, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Last Winter (L''hiver dernier)', 3, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Genocide', 2, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Coast Guard, The (Hae anseon)', 7, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Simone (S1m0ne)', 50, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Sleeping Beauty, The (La belle endormie)', 39, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Yamla Pagla Deewana 2', 34, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Ewok Adventure, The (a.k.a. Caravan of Courage: An Ewok Adventure)', 25, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('I Am David', 16, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Madonna of the Seven Moons', 10, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('The Five Man Army', 3, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('At the Death House Door', 38, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Glass Bottom Boat, The', 36, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Losers, The', 6, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Foo Fighters: Back and Forth', 43, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Talcum Powder', 30, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Alila', 34, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('London After Midnight', 29, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('House, The (A Casa)', 43, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Charles Bradley: Soul of America', 32, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Starship Troopers 3: Marauder', 18, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Crow: Salvation, The', 9, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Pine Flat', 1, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('My Darling Clementine', 35, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Exodus (Cheut ai kup gei)', 1, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Trouble with Bliss, The', 46, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Empire Records', 42, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Jean-Luc Cinema Godard', 39, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('My Son, My Son, What Have Ye Done', 48, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Cercle Rouge, Le (Red Circle, The)', 46, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Long Night, The', 46, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Certified Copy (Copie conforme)', 38, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Ballroom, The (Chega de Saudade)', 21, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('God''s Sandbox (Tahara)', 32, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('As Luck Would Have It (Chispa de la vida, La)', 50, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Good Advice', 27, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Sharknado', 26, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Prisoner of Zenda, The', 45, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Boy Friend, The', 40, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('41', 25, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Val Lewton:  The Man in the Shadows', 49, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Vengeance Can Wait', 41, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('American Werewolf in Paris, An', 30, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Charlie Chan in Reno', 28, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Riff-Raff', 8, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('12th & Delaware', 34, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Still Crazy', 33, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Crystal Ball, The', 6, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Missing in America', 1, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Barbara', 5, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Comes a Bright Day', 1, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Apart from You (After Our Separation) (Kimi to wakarete)', 23, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Without a Paddle: Nature''s Calling', 29, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Spasmo', 28, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Secret Ballot (Raye makhfi)', 33, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Best Laid Plans', 31, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Thirst (Bakjwi)', 38, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Welcome to Sarajevo', 10, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Mad Ron''s Prevues from Hell', 10, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Balance', 43, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Tempest', 21, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Third World Cop', 47, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Dark Ride', 40, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Penthouse', 11, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Berserk: The Golden Age Arc 3 - Descent', 50, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Amazing Adventure, The (a.k.a. The Amazing Quest of Ernest Bliss)', 36, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Helvetica', 5, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('GLOW: The Story of the Gorgeous Ladies of Wrestling', 1, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('I Am Sam', 39, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Chori Chori Chupke Chupke', 12, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Half of a Yellow Sun', 24, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Samurai Vendetta', 45, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Two Jakes, The', 44, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('From Morn to Midnight (Von morgens bis Mitternacht)', 3, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Alabama''s Ghost', 43, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Intimate Lighting (Intimni osvetleni)', 14, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Bye-Bye Bin Laden', 1, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Gamera vs. Jiger', 33, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Double Jeopardy', 23, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Nazis Strike, The (Why We Fight, 2)', 32, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Chloe', 35, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Alien Contamination', 48, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Battle for Marjah, The', 44, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Eddie and the Cruisers', 2, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('20 Seconds of Joy', 35, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Salaam Namaste', 19, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Enlightenment Guaranteed (Erleuchtung Garantiert)', 38, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Cartoonist: Jeff Smith, BONE and the Changing Face of Comics, The', 30, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Patent Leather Kid, The', 3, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Gold Raiders', 42, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Private Life of Henry VIII, The', 3, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Winter''s Bone', 20, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Shadowing the Third Man', 32, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Glitter', 32, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Me Myself I', 31, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Revolt in the Fifth Dimension', 48, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Tarnation', 14, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Wondrous Oblivion', 45, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Genesis', 24, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Doubt', 47, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Rustlers'' Rhapsody', 19, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Return of the Killer Tomatoes!', 29, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('From the Clouds to the Resistance (Dalla nube alla resistenza)', 15, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Sweet Sweetback''s Baadasssss Song', 5, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Geographer Drank His Globe Away, The (Geograf globus propil)', 21, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Third Miracle, The', 46, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Charlie Chan''s Greatest Case', 30, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Boot Camp', 31, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Black Roses ', 33, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('North West Frontier', 22, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Cranford', 21, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Light at the Edge of the World, The', 12, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Audition (Ôdishon)', 37, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Human Scale, The', 5, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Woman''s Tale, A', 18, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Halloween Tree, The', 20, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Cloudland', 50, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Something Borrowed', 46, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('28 Weeks Later', 46, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Women, The', 28, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Jack and Jill', 20, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Butch Cassidy and the Sundance Kid', 20, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Carmen Jones', 47, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Rainmaker, The', 7, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Opening Night', 4, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Earth', 5, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Dr. Moreau''s House of Pain', 14, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Cantante, El', 36, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Beyond Silence (Jenseits der Stille)', 43, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('In God We Teach', 49, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Jackass Number Two', 4, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Other Woman, The', 23, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Banklady', 22, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('The Batman vs. Dracula', 17, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('All I Want (Try Seventeen)', 16, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Secret of NIMH, The', 24, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Damsel in Distress, A', 33, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Mo', 3, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Late Bloomers', 23, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Brick Mansions', 43, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Haider', 3, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Broken Wings (Knafayim Shvurot)', 14, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('You, the Living (Du levande)', 16, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Man Who Fell to Earth, The', 15, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Golden Compass, The', 5, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Village People Radio Show (Apa khabar orang kampung)', 18, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Last Winter (L''hiver dernier)', 21, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Nightmare on Elm Street 5: The Dream Child, A', 16, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Living Sea, The', 3, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Bordertown', 4, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('From Beyond', 15, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Dave', 40, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Endeavour', 35, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Henry V', 29, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Winged Creatures (Fragments)', 25, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('New World (Shin-sae-gye)', 29, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Bright Lights (Adventures in Africa)', 27, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Hurricane, The', 32, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Ides of March, The', 40, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Roadkill (a.k.a. Roadkill: Move or Die)', 7, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('We and the I, The', 6, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Dead Birds', 23, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Stir of Echoes', 20, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Vexille (Bekushiru: 2077 Nihon sakoku)', 33, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Losers, The', 32, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Sinister', 40, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Day of the Falcon', 12, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Double Life, A', 42, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Alien Hunter', 46, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Contender, The', 16, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Federico Fellini''s Autobiography (Federico Fellini - un autoritratto ritrovato)', 30, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Kinbaku', 42, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Lights Out', 44, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('So Normal (Normais, Os)', 22, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Signos del zodiaco, Los', 31, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Maniac', 2, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Nazarin (Nazarín)', 27, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Thieves by Law (Ganavim Ba Hok)', 49, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('King Leopold''s Ghost', 50, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Blood: The Last Vampire', 28, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Kings Row', 7, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Delta of Venus', 38, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Dead Men Tell', 28, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Ex-Lady', 13, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('CQ', 45, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('$9.99', 49, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Dakota Skye', 2, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Buffalo Bill', 20, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Rich Man''s Wife, The', 40, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Coach Carter', 30, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Andrei Rublev (Andrey Rublyov)', 21, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Always Leave Them Laughing', 1, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('A Night at the Movies: The Horrors of Stephen King', 25, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Tennessee', 29, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Farah Goes Bang', 27, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Cold Comes the Night', 6, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Stuart Saves His Family', 29, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Babes on Broadway', 31, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Seventh Heaven', 29, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('According to Greta', 26, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('On the Waterfront', 34, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Last Movie, The', 40, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Gore Gore Girls, The', 5, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Ra.One', 16, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Dumb and Dumber To', 33, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Common Wealth (Comunidad, La)', 37, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Lonely Street', 3, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Heavenly Forest', 6, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Donovan''s Reef', 44, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Wrong Turn 3: Left for Dead', 10, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('The Hunchback of Paris', 23, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Sleeping Car Murder, The (Compartiment tueurs)', 11, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Red Chapel, The (Røde kapel, Det)', 11, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Cliffhanger', 12, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Cornelis', 37, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('3 Ninjas', 22, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Robin and Marian', 11, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Lonely Are the Brave', 31, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Black Dawn', 35, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Hero Wanted', 43, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('The House of Intrigue', 4, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Black Bread (Pa Negre)', 36, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Clueless', 45, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Cure, The', 38, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Whom the Gods Wish to Destroy (Nibelungen, Teil 1: Siegfried, Die)', 29, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Taking of Pelham 1 2 3, The', 34, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Pepi, Luci, Bom (Pepi, Luci, Bom y Otras Chicas del Montón)', 36, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Prestige, The', 14, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Redacted', 24, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Incident at Oglala', 7, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Dirty Ho (Lan tou He)', 32, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Love Parade, The', 7, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('My Dear Secretary', 25, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Westward Ho', 13, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('From Beginning to End (Do Começo ao Fim)', 35, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Sybil', 25, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Eerie Tales (Unheimliche Geschichten)', 23, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Fifth Commandment, The', 35, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Kamchatka', 31, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Lost Battalion, The', 10, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Project Moon Base', 49, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Go-Between, The', 47, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Inequality for All', 47, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Dimples', 22, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Chronicles of Riddick, The', 42, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('June 9 ', 7, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Gentlemen Broncos', 39, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Cameraman''s Revenge, The (Mest kinematograficheskogo operatora)', 38, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Nadine', 39, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Gas, Inspector Palmu! (Kaasua, komisario Palmu!)', 4, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Still Alice', 24, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Soul Food', 3, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Bachelor, The', 31, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Wuthering Heights', 45, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('18 Years Old and Rising (J''aime regarder les filles)', 32, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Paramore Live, the Final Riot!', 28, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Expendables, The', 19, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Rollerball', 23, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Cat''s Eye', 22, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Play Time (a.k.a. Playtime)', 40, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('The Best of Me', 48, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Witch''s Night Out', 5, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Jew in the Lotus, The', 22, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Death of a Salesman', 46, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Merry Christmas Mr. Lawrence', 11, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Formula, The', 36, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('In My Country (a.k.a. Country of My Skull)', 20, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Batman & Robin', 27, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Sordid Lives', 26, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Car Bonus (Autobonus)', 30, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Boulevard', 37, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Lewis Black: Stark Raving Black', 12, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('The Strength of Water', 15, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Zapped!', 38, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Forgetting Sarah Marshall', 3, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Dragon Seed', 26, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Burton and Taylor', 39, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Children of the Decree (Das Experiment 770 - Gebären auf Befehl)', 35, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Butterfly (La lengua de las mariposas)', 2, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Bunker, The', 49, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Tortured, The', 29, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Foreign Letters', 42, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Words, The', 31, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('3 Penny Opera, The (Threepenny Opera, The) (3 Groschen-Oper, Die)', 20, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Boy Meets Boy', 24, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Introduction to Physics, An', 34, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Modigliani', 2, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Dolphin Tale 2', 8, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('The Face of Marble', 48, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Jailhouse Rock', 22, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Rocco and His Brothers (Rocco e i suoi fratelli)', 2, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Hit, The', 32, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Hidden Agenda', 49, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('G.I. Joe: The Revenge of Cobra', 46, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Drag Me to Hell', 2, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Cathy Come Home', 21, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Sebastian', 24, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Friday Night (Vendredi Soir)', 39, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Get Rich or Die Tryin''', 25, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Milky Way, The', 10, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Double Wedding', 40, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Crime Wave', 41, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('She''s All That', 34, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Angst', 30, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Student of the Year', 21, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Rare Birds', 33, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Doodlebug', 20, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Respiro', 14, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('That Awkward Moment', 6, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Cry, The (Grido, Il)', 8, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('300: Rise of an Empire', 10, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Foxfire', 36, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Professionals, The', 28, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('99 River Street', 50, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Hide-Out', 35, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('House IV', 34, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Agnosia', 18, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Septième juré, Le', 49, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Ballerina (La mort du cygne)', 23, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Broken Bridges', 29, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Octopus, The (Le poulpe)', 3, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Common Man, A', 21, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Riders of the Purple Sage', 20, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Last Unicorn, The', 31, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Beauty and the Boss', 50, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Urban Ghost Story', 41, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Who''s Afraid of Virginia Woolf?', 11, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Torpedo Bombers (Torpedonostsy)', 6, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Holy Innocents, The (Santos inocentes, Los)', 26, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('California', 23, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Marie and Bruce', 29, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Juice', 41, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Ishq', 45, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Offender', 32, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('1990: The Bronx Warriors (1990: I guerrieri del Bronx)', 3, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Robin and the 7 Hoods', 24, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Divorcing Jack', 20, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Pittsburgh', 26, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Shark Skin Man and Peach Hip Girl (Samehada otoko to momojiri onna)', 50, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Good Ol'' Freda', 23, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Dead End Drive-In', 19, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Major Dundee', 23, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Lola', 19, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Shenandoah', 16, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Duo (Pas de deux)', 41, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Monster-in-Law', 40, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Fright Night', 7, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Cocoon', 29, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Ugly Duckling and Me!, The', 41, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Heartbreakers', 15, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Bounce', 44, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Summer Catch', 30, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Safe House', 8, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Diabolique (Les diaboliques)', 32, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Miller''s Crossing', 43, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Contact High', 9, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Fast Runner, The (Atanarjuat)', 37, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Stratosphere Girl', 3, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Front, The', 12, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('It Came from Outer Space', 36, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Best of Times, The (Mei li shi guang)', 30, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Wog Boy, The', 25, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Love Ranch', 26, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Scent of a Woman (Profumo di donna)', 37, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('My New Gun', 10, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('People, Places, Things', 32, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Conception', 44, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Paris by Night', 28, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Wisdom', 44, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('High Sierra', 36, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Bullet for a Badman (Renegade Posse)', 44, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Return of Jafar, The', 2, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Abendland', 38, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Butcher, The (Boucher, Le)', 24, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Messiah of Evil', 22, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Devil in the Flesh', 11, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Merlin', 9, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Beautiful Losers', 30, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Chasing Ghosts: Beyond the Arcade ', 5, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Chinese Odyssey 2002 (Tian xia wu shuang)', 25, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Safety Patrol', 49, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Wishmaster', 10, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Kings of the Sun', 41, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Life Without Dick', 45, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Palindromes', 20, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Pillow Talk', 2, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('My Stepmother Is an Alien', 18, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Fantastic Planet, The (Planète sauvage, La)', 27, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('The Horribly Slow Murderer with the Extremely Inefficient Weapon', 22, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('League of Their Own, A', 46, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Bomber', 21, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Khartoum', 48, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Blood of Redemption', 29, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('$ (Dollars)', 14, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Ruthless People', 36, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Two Jakes, The', 17, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Warlords, The (Tau ming chong)', 43, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Indecent Proposal', 13, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Night of the Day of the Dawn of the Son of the Bride of the Return of the Terror', 14, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Wrestling Ernest Hemingway', 9, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Snow (Snijeg)', 12, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Green Dolphin Street', 21, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Mujhse Shaadi Karogi', 7, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Betrayal', 18, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Three Marias, The (Três Marias, As)', 35, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Shiver of the Vampires, The (Frisson des vampires, Le)', 4, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('In the Loop', 18, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Tyler Perry''s Madea Goes to Jail', 4, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Love Without Pity', 14, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Facing Windows (Finestra di fronte, La)', 15, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('James Dean', 38, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Red Angel (Akai tenshi)', 12, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('This So-Called Disaster', 37, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Perfectly Normal', 8, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Istanbul', 8, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Army of One (Joshua Tree)', 42, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Boys and Girls', 3, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Inherent Vice', 42, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Punk Syndrome, The (Kovasikajuttu)', 22, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('My Friend Ivan Lapshin (Moy drug Ivan Lapshin)', 30, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Volcano (Eldfjall)', 32, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Future Weather', 25, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Raising Victor Vargas', 5, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Genevieve', 30, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Pokemon 4 Ever (a.k.a. Pokémon 4: The Movie)', 3, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('I Never Sang for My Father', 37, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Bonsái', 29, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Amira & Sam', 50, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Pitch Black', 34, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Eye for an Eye, An (Silmä silmästä)', 33, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Belle époque', 27, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Frankenhooker', 23, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Faust', 35, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Assault on Precinct 13', 34, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Lightnin''', 21, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Naked Face, The', 6, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Air Hawks', 50, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('The Final Girl', 49, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Tree of Life, The', 38, 'Novell');
insert into books (pealkiri, autor_id, zanr) values ('Assignment, The', 40, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('Back in the Day', 18, 'Romaan');
insert into books (pealkiri, autor_id, zanr) values ('She Wouldn''t Say Yes', 5, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Fantasia 2000', 50, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Doomwatch', 48, 'Draama');
insert into books (pealkiri, autor_id, zanr) values ('Madeinusa', 28, 'Aajalugu');
insert into books (pealkiri, autor_id, zanr) values ('Ismael', 22, 'Komöödia');
insert into books (pealkiri, autor_id, zanr) values ('Beyond Rangoon', 5, 'Rahvaluule');
insert into books (pealkiri, autor_id, zanr) values ('Deconstructing Harry', 46, 'Draama');
